name: "Release to NPM"
description: "Tag and Publish your package to npm"
inputs:
  version:
    description: "Version (major | minor | patch)"
    required: true
    default: "minor"
  auth_token:
    description: "NODE_AUTH_TOKEN"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org
        cache: yarn

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
      shell: bash

    - name: Make release branch
      run: git checkout -b release
      shell: bash

    - name: Tag new release
      run: yarn version --${{ inputs.version }}
      shell: bash

    - run: git checkout main
      shell: bash

    - name: Merge release branch
      run: git merge --ff-only release
      shell: bash

    - run: git push
      shell: bash

    - run: git push --tags
      shell: bash

    - name: Publish to NPM
      run: yarn publish --access public
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.auth_token }}
