name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
