name: Publish

on:
  push:
    branches: main
    tags: v*

jobs:
  all:
    name: all
    runs-on: ubuntu-latest
    steps:
      - name: Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
