name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (major | minor | patch)"
        required: true
        default: "minor"

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - uses: .
        with:
          version: ${{ github.event.inputs.version }}
