name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (major | minor | patch)"
        required: true
        default: "minor"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Configure git
        run: |
          git config user.name "John Doe"
          git config user.email "john.doe@example.com"

      - name: Make release branch
        run: git checkoub -b release

      - name: Tag new release
        run: yarn version --${{ github.event.inputs.version }}

      - name: Bump dev version
        run: yarn version --prerelease --preid dev

      - name: Merge release branch

      - run: git push
      - run: git push --tags
