on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to increment"
        required: true
        default: "minor"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: bump version
        run: yarn version --${{ github.event.inputs.version }}"

      - name: push
        run: git push

      - name: push tags
        run: git push --tags

      - name: Publish to NPM
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
