name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to increment"
        required: true
        default: "minor"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Configure git
        run: |
          git config user.name "John Doe"
          git config user.email "john.doe@example.com"

      - name: bump version
        run: yarn version --${{ github.event.inputs.version }}

      - name: push
        run: git push

      - name: push tags
        run: git push --tags
